import type { OperationalResponseEvidence } from "./vehicleDynamics";

export type EngineeringResponseArtifact = {
  artifact_type: "engineering_response";
  artifact_id: string;
  artifact_sha256: string;
  case_id: string;
  case_revision_sha256: string;
  run_id: string;
  session_id: string;
  setup_id: string;
  source_recording_sha256: string;
  source_producer_id: string;
  relation: string;
  lap_pct_start: number;
  lap_pct_end: number;
  phase: string;
  canonical_clock_contract: "qualified_session_tick";
  source_lap_numbers: number[];
  reference_lap_numbers: number[];
  independence_unit_ids: string[];
  operational_evidence: OperationalResponseEvidence;
  applicability: "exact_current_case";
  blocker_reasons: string[];
  authority_ceiling: "observation_only";
  p19_support_authorized: false;
  component_support_authorized: false;
  setup_authorized: false;
};

export type CanonicalEngineeringCase = {
  schema_version: "p3543.canonical-engineering-case.v1";
  case_id: string;
  case_sha256: string;
  case_revision_sha256: string;
  run_id: string;
  session_id: string;
  recording_sha256: string;
  setup_id: string;
  setup_snapshot_sha256: string;
  objective_id: string;
  condition_epoch_sha256: string;
  p19_reasoning_snapshot_sha256: string;
  p20_state_revision: string;
  p26_knowledge_graph_sha256: string;
  p32_projection_sha256: string;
  p35_assessment_sha256: string;
  p351_projection_sha256: string;
  p33_projection_sha256: string;
  evidence_index_sha256: string;
  primary_opportunity_id: string | null;
  response_artifacts: EngineeringResponseArtifact[];
  p19_response_admissions: Array<{
    admission_id: string;
    admission_sha256: string;
    case_id: string;
    case_revision_sha256: string;
    response_artifact_id: string;
    p19_reasoning_snapshot_sha256: string;
    assessments: Array<{
      cause_id: string;
      matched_mechanism_ids: string[];
      result: "supports_existing_contract" | "contradicts_existing_contract" | "unresolved" | "blocked";
      basis: string;
      blocker_reasons: string[];
      rank_modified: false;
      setup_authorized: false;
    }>;
    state: "admitted" | "unresolved" | "blocked";
    blocker_reasons: string[];
    authority: "p19_response_adapter_only";
    reasoning_rank_modified: false;
    terminal_action_modified: false;
    setup_authorized: false;
  }>;
  mechanism_ids: string[];
  component_ids: string[];
  effect_readiness: Array<{
    effect_id: string;
    bridge_id: string;
    state: "knowledge_only" | "measurement_ready" | "response_evidence_ready" | "p19_testable" | "blocked";
    response_artifact_ids: string[];
    expected_response_relation_ids: string[];
    exact_control_keys: string[];
    experiment_factor_id: string | null;
    countereffect_measurement_ids: string[];
    missing_evidence: string[];
    authority: "knowledge_only" | "measurement_only" | "exact_p19_projection";
    setup_authorized: boolean;
  }>;
  active_discriminator_id: string | null;
  investigation_id: string | null;
  workspace_revision: string;
  terminal_move_sha256: string;
  capability_resolutions: Array<{
    resolution_id: string;
    missing_evidence: string;
    required_channel_ids: string[];
    status: "available_now" | "requires_new_run" | "pit_snapshot_only" | "structurally_unavailable";
    recovery: string;
    source_artifact_ids: string[];
    authority: "measurement_routing_only";
    setup_authorized: false;
  }>;
  quantity_observability: Array<{
    quantity_id: string;
    component_family_ids: string[];
    response_artifact_ids: string[];
    state: "currently_observable";
    authority: "quantity_observation_only";
    component_support_authorized: false;
    setup_authorized: false;
  }>;
  semantic_focus: {
    case_id: string;
    case_revision_sha256: string;
    artifact_id: string | null;
    lap_numbers: number[];
    lap_pct_start: number | null;
    lap_pct_end: number | null;
    phase: string | null;
    mechanism_ids: string[];
    response_relation_id: string | null;
    component_ids: string[];
    effect_ids: string[];
    control_keys: string[];
    p19_cause_ids: string[];
    authority: "navigation_only";
  };
  campaign_capture: {
    state: "pending" | "rejected" | "qualified" | "duplicate" | "corrupt";
    blocker_reasons: string[];
    historical_count_credited: false;
    null_count_credited: false;
    negative_control_count_credited: false;
    subgroup_count_credited: false;
    authority: "qualification_only";
  };
  authority: "case_receipt_only";
  p19_authority_unchanged: true;
  setup_authorized: false;
};
